[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pathfinding = "4.0.0"
regex = "1"
itertools = "0.10.5"
rayon = "1.6.1"
